# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

# User settings
username: Oleg Chernyshenko
user_description: >
  I am a software developer based in Christchurch, New Zealand. 
  My interests, including, but not limited to, software architecture, Swift, iOS development, mobile analytics and monetization.
  When I am not programming, you can find me hiking in the mountains or doing rock climbing in the climbing gym.
user_description2: Use the contacts provided above if you want to hire me for a contract work.
user_title: Software Developer
email: oleg@tugboat.nz
twitter_username: olegcode
github_username:  Peyotle
linkedin_username: chernyshenko
youtube: 
  
digital-ocean-referral: 'https://m.do.co/c/58ba5afc4659'
# Google-analytics
google-analytics:
  id: "UA-105774958-1"

exclude: ['package.json', 'src' , 'node_modules']
